---
title: "Лабораторная работа 3"
output: html_notebook
---

```{r}
  #1

  nu = c(968, 1026, 1021, 974, 1014, 1046, 1021, 970, 948, 1014)
  n = sum(nu)
  p = 1/10 # H0
  alpha = 0.05
  r = length(nu)
  
  P_n_nu = sum((nu-n*p)^2 / (n*p))
  
  q = qchisq(1 - alpha, df=(r-1))
  
  if (P_n_nu < q) {
    cat("HO accepted with alpha = ", alpha, "\n")
  }
  
  p_value = 1 - pchisq(P_n_nu, df=(r-1))
  cat("p_value = ", p_value)
  
```
```{r}
  #2
  n = 576
  x_i = c(0, 1, 2, 3, 4, 5, 6, 7)
  nu = c(229, 211, 93, 35, 7, 0, 0, 1)
  r = length(nu)
  lambda = sum(x_i) / length(x_i)
  
  P_n_nu = sum((nu - n*ppois(x_i, lambda=lambda))/ (n*ppois(x_i, lambda=lambda)))
  
  p_value = 1 - pchisq(P_n_nu, df=(r-1))
  cat("p_value = ", p_value)
  
```
```{r}
  #3
  n = 50
  alpha = 0.1
  x_i = c(-0.5, 0.5, 1.5, 3.5)
  nu = c(7, 25, 8, 10)
  #estimate params mu sigma_sq
  
```

```{r}
  #4
  alpha = 0.05
  r = 2
  s = 4

  m = matrix(c(9, 8, 5, 4,  3, 5, 9, 11), nrow=r, ncol=s, byrow=TRUE)
  nui = rowSums(m)
  nj = colSums(m)

  
  P_n_nu = 0
  for (i in 1:r) {
    for (j in 1:s) {
      P_n_nu = P_n_nu + (m[i, j]**2 / (nj[j] * nui[i]))
    }
  }
  
  P_n_nu = sum(nj) * (P_n_nu - 1)
  
  q = qchisq(1 - alpha, df=(r - 1) * (s - 1))
  
  if (P_n_nu < q) {
    cat("HO accepted with alpha = ", alpha, "\n")
  } else {
    cat("HO rejected with alpha = ", alpha, "\n")
  }
  
  p_value = 1 - pchisq(P_n_nu, df=(r - 1) * (s - 1))
  cat("p_value = ", p_value)
  
```
```{r}
  #5
  alpha = 0.1
  r = 2
  s = 3

  m = matrix(c(17, 22, 11, 43, 78, 29), nrow=r, ncol=s, byrow=TRUE)
  nui = rowSums(m)
  nuj = colSums(m)
  
  
  P_n_nu = 0
  for (i in 1:r) {
    for (j in 1:s) {
      P_n_nu = P_n_nu + (m[i, j]**2 / (nuj[j] * nui[i]))
    }
  }
  
  P_n_nu = sum(nuj) * (P_n_nu - 1)
  
  q = qchisq(1 - alpha, df = (r - 1) * (s - 1))
  
  if (P_n_nu < q) {
    cat("HO accepted with alpha = ", alpha, "\n")
  } else {
    cat("HO rejected with alpha = ", alpha, "\n")
  }
  
```
```{r}
  #6
  alpha = 0.001
  r = 3
  s = 4

  m = matrix(c(1768, 807, 189, 47, 115, 438, 288, 16, 946, 1387, 746, 53), nrow=r, ncol=s, byrow=TRUE)
  nui = rowSums(m)
  nuj = colSums(m)
  
  
  P_n_nu = 0
  for (i in 1:r) {
    for (j in 1:s) {
      P_n_nu = P_n_nu + (m[i, j]**2 / (nuj[j] * nui[i]))
    }
  }
  
  P_n_nu = sum(nuj) * (P_n_nu - 1)
  
  q = qchisq(1 - alpha, df = (r - 1) * (s - 1))
  
  if (P_n_nu < q) {
    cat("HO accepted with alpha = ", alpha, "\n")
  } else {
    cat("HO rejected with alpha = ", alpha, "\n")
  }
  
  p_value = 1 - pchisq(P_n_nu, df=(r - 1) * (s - 1))
  cat("p_value = ", p_value)

```

```{r}
  #7
  alpha = 0.01
  r = 0
  s = 3

  # разбить на группы
  
  arr1 = c(182, 169, 182, 176, 180, 170, 174, 182, 173, 182, 180, 168, 165)
  arr2 = c(167, 170, 164, 188, 182, 190, 162, 164, 160, 167, 163, 185, 156, 194, 174, 161, 185, 159, 161, 189, 167, 184, 184)
  arr3 = c(178, 186, 159, 167, 166, 164, 160, 164, 159, 172, 168, 170, 156, 158, 170, 176)
  
  minn = min(arr1, arr2, arr3)
  maxx = max(arr1, arr2, arr3)
  
  X = seq.int(minn, maxx, 5)
  r = length(X)
  print(X)
  
  m = matrix(c(0), nrow=r, ncol=s)
  
  for (i in 1:(r-1)) {
    
    for(a1 in arr1) {
     if(a1 >= X[i] && a1 < X[i+1]) {
       m[i, 1] = m[i, 1] + 1
     }
    }
    for(a2 in arr2) {
      if(a2 >= X[i] && a2 < X[i+1]){
        m[i, 2] = m[i, 2] + 1
      }
    }
    for(a3 in arr3) {
      if(a3 >= X[i] && a3 < X[i+1]){
        m[i, 3] = m[i, 3] + 1
      }
    }
  }
  
  for (a1 in arr1) {
    if(a1 >= X[r]) {
      m[r, 1] = m[r, 1] + 1
    }
  }
  
  
  for (a2 in arr2) {
    if(a2 >= X[r]) {
      m[r, 2] = m[r, 2] + 1
    }
  }
  
  
  for (a3 in arr3) {
    if(a3 >= X[r]) {
      m[r, 3] = m[r, 3] + 1
    }
  }
  
  nui = rowSums(m)
  nuj = colSums(m)
  
  
  nui = rowSums(m)
  nj = colSums(m)

  
  P_n_nu = 0
  for (i in 1:r) {
    for (j in 1:s) {
      P_n_nu = P_n_nu + (m[i, j]**2 / (nj[j] * nui[i]))
    }
  }
  
  P_n_nu = sum(nj) * (P_n_nu - 1)
  
  q = qchisq(1 - alpha, df=(r - 1) * (s - 1))
  
  if (P_n_nu < q) {
    cat("HO accepted with alpha = ", alpha, "\n")
  } else {
    cat("HO rejected with alpha = ", alpha, "\n")
  }
  
  p_value = 1 - pchisq(P_n_nu, df=(r - 1) * (s - 1))
  cat("p_value = ", p_value)
```

```{r}
  #8
```


