---
title: "Лабораторная работа 3"
output: html_notebook
---

```{r}
  Y <- function(x, teta, eps) {
    return (teta[1] + teta[2]*x + teta[3]*x**2 + teta[4]*x**3 + teta[5]*x**4 + eps)
  }
```



```{r}
  #1
  a = 0
  b = 10
  n = 50
  m = 5
  
  mean = 0
  sd = 20
  
  tetas <- c(1, -5, 20, -1, -0.1)
  x <- seq(a, b, (b - a) / n)
```


```{r}
  #2
  eps <- rnorm(n + 1, mean=mean, sd=sd)
  Y <- Y(x, teta=tetas, eps=eps)
```


```{r}

  #install.packages("ggplot2")
  library(ggplot2)
  
  
  df <- data.frame(Y, x)
  ggplot(data=df, aes(x=x, y=Y))  + geom_line()

```

```{r}
#3
  X_mat = matrix(1, nrow = n + 1, ncol = 5)
  
  for (i in 1:(n + 1)) {
    for (j in 1:m) {
      X_mat[i, j] = x[i]**(j - 1) 
    }
  }
  
  B = t(X_mat) %*% X_mat
  library(pracma)
  B_inv = inv(B)
  
  
  Tetas_LS = B_inv %*% t(X_mat) %*% Y
  
  print(Tetas_LS)
 
```


```{r}
  Y_cap <- function(x) {
    return (Tetas_LS[1] + Tetas_LS[2]*x + Tetas_LS[3]*x**2 + Tetas_LS[4]*x**3 + Tetas_LS[5]*x**4)
  }
```


```{r}
  Y_cap <- Y_cap(x)
```

```{r}
  df <- data.frame(Y_cap, Y, x)
  ggplot(data=df, aes(x))  + geom_line(aes(y=Y), color='blue') + geom_line(aes(y=Y_cap), color='red')
```
```{r}
  #4
  
  RSS = t(Y - X_mat %*% Tetas_LS) %*% (Y - X_mat %*% Tetas_LS)

  Siqma_square = RSS/(n - m)
  print(Siqma_square)

```

```{r}
  #5

  alpha = 0.01
  
  q1 = qchisq(alpha/2, df=(n - m))
  q2 = qchisq(1 - alpha/2, df=(n - m))
  cat("Квантиль 1", q1, "\n")
  cat("Квантиль 2", q2, "\n")
  
  cat("Доверительный интервал [", RSS/q2, ",", RSS/q1, "]", "с уровнем значимости ", alpha, "\n")
  
```
```{r}
  
  q = qt(1-alpha/2, df=(n - m))

  cat("Квантиль ", q, "\n")

  
  for (i in 1:m) {
    cat("Доверительный интервал для teta" , i,  "[", Tetas_LS[i] - q * sqrt(Siqma_square * B_inv[i, i]), "," , Tetas_LS[i] + q * sqrt(Siqma_square * B_inv[i, i]), "] с уровнем значимости ", alpha, "\n")
  }
  
```
```{r}
  #6
  for (i in 1:m) {
    if(abs(tetas[i]/(sqrt(Siqma_square * B_inv[i, i]))) <= q) {
      cat("H0 для teta[", i, "] = ", tetas[i],"\n")
    }
    else {
      cat("H1 для teta[", i, "] = ", tetas[i], "\n")
    }
  }
```
```{r}
  #7
  Y_bar = 1/n * sum(Y)
  
  cat("d = ", 1 - RSS/(sum((Y-Y_bar)^2)))
```
```{r}
  #8

```

